# Generated by Django 6.0.2 on 2026-02-21 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, '💰 Salary'), (2, '💼 Business'), (3, '📈 Investment'), (4, '🏠 Rent'), (5, '🎁 Gift'), (6, '💻 Freelance'), (7, '💰 Bonus'), (8, '💵 Refund'), (9, '📊 Dividend'), (10, '🏆 Prize'), (11, '💼 Consulting'), (12, '💰 Allowance'), (13, '💵 Commission'), (14, '💰 Interest'), (15, '💵 Other Income'), (16, '🍔 Food & Dining'), (17, '🚗 Transportation'), (18, '🏠 Rent/Utilities'), (19, '📱 Shopping'), (20, '🎬 Entertainment'), (21, '🏥 Healthcare'), (22, '📚 Education'), (23, '✈️ Travel'), (24, '💪 Fitness'), (25, '🐾 Pets'), (26, '📦 Insurance'), (27, '📱 Mobile/Internet'), (28, '💇 Personal Care'), (29, '🎁 Gifts'), (30, '💵 Other Expenses')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deadline', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('category', models.IntegerField(choices=[(1, '💰 Salary'), (2, '💼 Business'), (3, '📈 Investment'), (4, '🏠 Rent'), (5, '🎁 Gift'), (6, '💻 Freelance'), (7, '💰 Bonus'), (8, '💵 Refund'), (9, '📊 Dividend'), (10, '🏆 Prize'), (11, '💼 Consulting'), (12, '💰 Allowance'), (13, '💵 Commission'), (14, '💰 Interest'), (15, '💵 Other Income'), (16, '🍔 Food & Dining'), (17, '🚗 Transportation'), (18, '🏠 Rent/Utilities'), (19, '📱 Shopping'), (20, '🎬 Entertainment'), (21, '🏥 Healthcare'), (22, '📚 Education'), (23, '✈️ Travel'), (24, '💪 Fitness'), (25, '🐾 Pets'), (26, '📦 Insurance'), (27, '📱 Mobile/Internet'), (28, '💇 Personal Care'), (29, '🎁 Gifts'), (30, '💵 Other Expenses')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
